<a href="https://colab.research.google.com/github/layds120/Tugas3_DM_Preprocessing/blob/main/TUGAS3_DM_Preprocessing_A11201911972.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dian Laila Shifa

---


A11.2019.11972

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('BMI.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Laras' 80.0 24.7]
 ['Budi' 55.0 22.9]
 ['Lesti' 50.0 nan]
 ['Budi' 42.0 18.7]
 ['Lesti' 75.0 29.3]
 ['Lesti' nan 19.6]
 ['Laras' 65.0 19.0]
 ['Budi' 50.0 17.3]
 ['Lesti' 65.0 16.5]
 ['Laras' 60.0 25.4]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
print(x_train)

[['Lesti' 75.0 29.3]
 ['Laras' 60.0 25.4]
 ['Budi' 55.0 22.9]
 ['Laras' 65.0 19.0]
 ['Budi' 50.0 17.3]
 ['Budi' 42.0 18.7]
 ['Laras' 80.0 24.7]
 ['Lesti' nan 19.6]]


In [ ]:
print(x_test)

[['Lesti' 50.0 nan]
 ['Lesti' 65.0 16.5]]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Laras' 80.0 24.7]
 ['Budi' 55.0 22.9]
 ['Lesti' 50.0 21.48888888888889]
 ['Budi' 42.0 18.7]
 ['Lesti' 75.0 29.3]
 ['Lesti' 60.22222222222222 19.6]
 ['Laras' 65.0 19.0]
 ['Budi' 50.0 17.3]
 ['Lesti' 65.0 16.5]
 ['Laras' 60.0 25.4]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 0.0 80.0 24.7]
 [1.0 0.0 0.0 55.0 22.9]
 [0.0 0.0 1.0 50.0 21.48888888888889]
 [1.0 0.0 0.0 42.0 18.7]
 [0.0 0.0 1.0 75.0 29.3]
 [0.0 0.0 1.0 60.22222222222222 19.6]
 [0.0 1.0 0.0 65.0 19.0]
 [1.0 0.0 0.0 50.0 17.3]
 [0.0 0.0 1.0 65.0 16.5]
 [0.0 1.0 0.0 60.0 25.4]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 2 0 1 0 2 2 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 65.0 19.0]
 [0.0 0.0 1.0 75.0 29.3]
 [0.0 1.0 0.0 80.0 24.7]
 [1.0 0.0 0.0 42.0 18.7]
 [1.0 0.0 0.0 55.0 22.9]
 [1.0 0.0 0.0 50.0 17.3]
 [0.0 0.0 1.0 65.0 16.5]
 [0.0 0.0 1.0 60.22222222222222 19.6]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 50.0 21.48888888888889]
 [0.0 1.0 0.0 60.0 25.4]]


In [ ]:
print(y_train)

[2 0 0 1 2 0 0 2]


In [ ]:
print(y_test)

[0 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:,3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 1.8520869081516291 0.25144742283748456]
 [0.0 1.0 0.0 1.333214311315375 0.8261843893231647]
 [0.0 1.0 0.0 -0.2234034791933881 1.400921355808845]
 [0.0 1.0 0.0 -0.7422760760296424 -0.3232895436481943]
 [0.0 0.0 1.0 -1.2611486728658967 -1.7601319598623935]
 [0.0 0.0 1.0 -0.7422760760296424 -1.1853949933767145]
 [0.0 1.0 0.0 -0.2234034791933881 0.8261843893231647]
 [1.0 0.0 0.0 0.007206563844946338 -0.03592106040535421]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 -0.980698401168828 0.12063977867626013]
 [0.0 1.0 0.0 -0.1299720772633387 1.085758008086337]]
